name: dexa
description: A Dart implementation of exa
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  flutter_lints: ^2.0.0
dependencies:
  args: ^2.4.0
  intl: ^0.18.0
  mime: ^1.0.0
  path: ^1.8.0
